//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimedRebecaCode }
     * 
     * @return
     *     the new instance of {@link TimedRebecaCode }
     */
    public TimedRebecaCode createTimedRebecaCode() {
        return new TimedRebecaCode();
    }

    /**
     * Create an instance of {@link MailboxDeclaration }
     * 
     * @return
     *     the new instance of {@link MailboxDeclaration }
     */
    public MailboxDeclaration createMailboxDeclaration() {
        return new MailboxDeclaration();
    }

    /**
     * Create an instance of {@link TimedRebecaParentSuffixPrimary }
     * 
     * @return
     *     the new instance of {@link TimedRebecaParentSuffixPrimary }
     */
    public TimedRebecaParentSuffixPrimary createTimedRebecaParentSuffixPrimary() {
        return new TimedRebecaParentSuffixPrimary();
    }

}
