//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.MainDeclaration;


/**
 * <p>Java class for TimedMainDeclaration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TimedMainDeclaration">
 *   <complexContent>
 *     <extension base="{http://rebecalang.org/compiler/modelcompiler/corerebeca}MainDeclaration">
 *       <sequence>
 *         <element name="mainMailboxDefinition" type="{http://rebecalang.org/compiler/modelcompiler/timedrebeca}MainMailboxDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="mainNetworkDefinition" type="{http://rebecalang.org/compiler/modelcompiler/timedrebeca}MainNetworkDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimedMainDeclaration", propOrder = {
    "mainMailboxDefinition",
    "mainNetworkDefinition"
})
public class TimedMainDeclaration
    extends MainDeclaration
{

    protected List<MainMailboxDefinition> mainMailboxDefinition;
    protected List<MainNetworkDefinition> mainNetworkDefinition;

    /**
     * Gets the value of the mainMailboxDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the mainMailboxDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMainMailboxDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MainMailboxDefinition }
     * 
     * 
     * @return
     *     The value of the mainMailboxDefinition property.
     */
    public List<MainMailboxDefinition> getMainMailboxDefinition() {
        if (mainMailboxDefinition == null) {
            mainMailboxDefinition = new ArrayList<>();
        }
        return this.mainMailboxDefinition;
    }

    /**
     * Gets the value of the mainNetworkDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the mainNetworkDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMainNetworkDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MainNetworkDefinition }
     * 
     * 
     * @return
     *     The value of the mainNetworkDefinition property.
     */
    public List<MainNetworkDefinition> getMainNetworkDefinition() {
        if (mainNetworkDefinition == null) {
            mainNetworkDefinition = new ArrayList<>();
        }
        return this.mainNetworkDefinition;
    }

}
