//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.RebecaCode;


/**
 * <p>Java class for TimedRebecaCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TimedRebecaCode">
 *   <complexContent>
 *     <extension base="{http://rebecalang.org/compiler/modelcompiler/corerebeca}RebecaCode">
 *       <sequence>
 *         <element name="mailboxDeclaration" type="{http://rebecalang.org/compiler/modelcompiler/timedrebeca}MailboxDeclaration" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="networkDeclaration" type="{http://rebecalang.org/compiler/modelcompiler/timedrebeca}NetworkDeclaration" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimedRebecaCode", propOrder = {
    "mailboxDeclaration",
    "networkDeclaration"
})
public class TimedRebecaCode
    extends RebecaCode
{

    protected List<MailboxDeclaration> mailboxDeclaration;
    protected List<NetworkDeclaration> networkDeclaration;

    /**
     * Gets the value of the mailboxDeclaration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the mailboxDeclaration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMailboxDeclaration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MailboxDeclaration }
     * 
     * 
     * @return
     *     The value of the mailboxDeclaration property.
     */
    public List<MailboxDeclaration> getMailboxDeclaration() {
        if (mailboxDeclaration == null) {
            mailboxDeclaration = new ArrayList<>();
        }
        return this.mailboxDeclaration;
    }

    /**
     * Gets the value of the networkDeclaration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the networkDeclaration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkDeclaration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkDeclaration }
     * 
     * 
     * @return
     *     The value of the networkDeclaration property.
     */
    public List<NetworkDeclaration> getNetworkDeclaration() {
        if (networkDeclaration == null) {
            networkDeclaration = new ArrayList<>();
        }
        return this.networkDeclaration;
    }

}
