//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.Expression;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.MainRebecDefinition;


/**
 * <p>Java class for TimedMainRebecDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TimedMainRebecDefinition">
 *   <complexContent>
 *     <extension base="{http://rebecalang.org/compiler/modelcompiler/corerebeca}MainRebecDefinition">
 *       <sequence>
 *         <element name="mailbox" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimedMainRebecDefinition", propOrder = {
    "mailbox"
})
public class TimedMainRebecDefinition
    extends MainRebecDefinition
{

    @XmlElement(required = true)
    protected Expression mailbox;

    /**
     * Gets the value of the mailbox property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getMailbox() {
        return mailbox;
    }

    /**
     * Sets the value of the mailbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setMailbox(Expression value) {
        this.mailbox = value;
    }

}
